use std::str::FromStr;
use crate::{Expr, Stmt};

grammar;

pub Stmt: Stmt = {
    AssignStmt,
    ExprStmt,
    IfStmt,
};

AssignStmt: Stmt = {
    <var:Ident> "=" <expr:Expr> => Stmt::Assign(var, expr),
};

ExprStmt: Stmt = {
    <expr:CallExpr> => Stmt::Expr(expr),
};

IfStmt: Stmt = {
    "if" <cond:CompareExpr> "{" <body:Stmt*> "}" => Stmt::If(cond, body),
};

pub Expr: Expr = {
    Num,
    Str,
    Ident => Expr::Var(<>),
};

CompareExpr: Expr = {
    <l:Ident> "==" <r:NumLit> => Expr::Eq(Box::new(Expr::Var(l)), Box::new(Expr::Num(r))),
};

NumLit: i32 = {
    r"[0-9]+" => i32::from_str(<>).unwrap(),
};

CallExpr: Expr = {
    <func:Ident> "(" <name:Ident> ":" <value:Str> ")" => {
        Expr::Call(func, vec![(name, value)])
    },
};

Num: Expr = {
    r"[0-9]+" => Expr::Num(i32::from_str(<>).unwrap()),
};

Str: Expr = {
    r#""[^"]*""# => Expr::Str(<>[1..<>.len()-1].to_string()),
};

Ident: String = {
    r"[a-zA-Z_][a-zA-Z0-9_]*" => <>.to_string(),
};