use std::str::FromStr;
use crate::{Expr, Stmt};

grammar;

pub Stmt: Stmt = {
    <var:Ident> "=" <expr:Expr> => Stmt::Assign(var, expr),
    <expr:Expr> => Stmt::Expr(expr),
};

pub Expr: Expr = {
    Num,
    Str,
    Ident => Expr::Var(<>),
    <l:Expr> "+" <r:Num> => Expr::Add(Box::new(l), Box::new(r)),
    <func:Ident> "(" <args:Comma<NamedArg>> ")" => Expr::Call(func, args),
};

Num: Expr = {
    r"[0-9]+" => Expr::Num(i32::from_str(<>).unwrap()),
};

Str: Expr = {
    r#""[^"]*""# => Expr::Str(<>[1..<>.len()-1].to_string()),
};

NamedArg: (String, Expr) = {
    <name:Ident> ":" <expr:Expr> => (name, expr),
};

Comma<T>: Vec<T> = {
    <mut v:(<T> ",")*> <e:T?> => match e {
        None => v,
        Some(e) => {
            v.push(e);
            v
        }
    }
};

Ident: String = {
    r"[a-zA-Z_][a-zA-Z0-9_]*" => <>.to_string(),
};