name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build_windows:
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
      - name: Run build
        run: xmake.cmd build
        shell: cmd

  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run build
        run: ./xmake.cmd build

  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
      - name: Run build
        run: ./xmake.cmd build
